apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170231400
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170231400
    app.kubernetes.io/part-of: test-app-170231400
  name: java-quarkus-170231400
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170231400
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170231400
    spec:
      containers:
      - image: quay.io/hacdev/0pijyw7m-tenant/test-app-170231400/java-quarkus-170231400@sha256:7816cb9fa7cec2b305a5c20ab5fe9610ad2138158fac92f8aa8a6b79b73c7671
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
